var myString;
var myNum;
var myBool;
var myVar;
let strArr: string[];
let numArr: number[];
let boolarr: boolean[];
let strrArr: Array<string>;
let numArr: Array<number>;
let boolarr: Array<boolean>;
myString = "jj";
myNum = 28;
myBool = false;
myVar = true;
strArr = ["hello", "world"];
numArr = [1, 2];
boolarr = [true, false, true];
let strNumberTuple: [string, number];
strNumberTuple = ["ejewj", 3];
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
console.log(myVoid);
